version: '2'

services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:80"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - ./src/assets:/static
    depends_on:
      - web

  web:
    build: .
    container_name: dg01
    command: bash -c "python manage.py collectstatic --noinput --settings=quizz.settings.server  && gunicorn quizz.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./src:/src
    expose:
      - "8000"